baseURL: "https://awakenedhaki.github.io/"
title: Awakened Haki
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Awakened Haki
  description: "Yet another nerdtastic blog...!"
  keywords: [Blog, Portfolio, PaperMod]
  author: Rodrigo Vallejos
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  # label:
  #   text: "Home"
  #   icon: /apple-touch-icon.png
  #   iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Awakened Haki
    subtitle: "Yet another nerdtastic blog...!"
    imageUrl: "https://msavatar1.nexon.net/Character/BJHHLCFHDCFBKLGCBMFDFDOLKPHDCIENLJBFCCHEMIHLEIEGBJPCDPCLEIEKNPEPAEAAKGFEHCLGAPLEPMFKFLAJNIDPDFLACLBBNPOADNELHNGAFBEICIPDJGMPEOBPBEPBNJAAEHIAEBOCDIEKBDAKFIMGJEDGMFOLCELPBLKGKPFPEGIPIDLLBLIKFAEDNNLHPCNLEBDJMFENCBFJIOILKFNDJHPDCDAAIIHCIHGPALAJBOBPCEFGGBHCLIKP.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts/
      - name: Tags
        url: tags/

  # home-info mode
  homeInfoParams:
    Title: "Greetings!"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/awakenedhaki"
    - name: github
      url: "https://github.com/awakenedhaki"
    - name: linkedin
      url: "https://linkedin.com/in/rodrigovallejosch"
    - name: kaggle
      url: "https://kaggle.com/awakenedhaki"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/awakenedhaki/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

permalinks:
  posts: /:year/:month/:title/

outputs:
    home:
        - HTML
        - RSS
        - JSON

menu:
    main:
        - name: Archive
          url: archives/
          weight: 5
        - name: Search
          url: search/


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true